Vagrant.configure(2) do |config|
  #cluster definition
  config.cluster.compose('dev-CDH') do |c|
    c.nodes(4, '5.14-') do |n|
      n.box = "ubuntu/xenial64"
      n.cpus = 1
      n.memory = 3072
    end
  end

  config.hostmanager.enabled = false
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true

  #cluster creation
  config.cluster.nodes.each do |node|
    config.vm.define "#{node.boxname}" do |node_vm|
      node_vm.vm.box = "#{node.box}"
      node_vm.vm.network :private_network, ip: "#{node.ip}"
      node_vm.vm.hostname = "#{node.fqdn}"
      node_vm.hostmanager.aliases = node.aliases unless node.aliases.empty?
      node_vm.vm.provision :hostmanager

      node_vm.vm.provider "virtualbox" do |vb|
        vb.name = "#{node.boxname}"
        vb.memory = node.memory
        vb.cpus = node.cpus
        vb.linked_clone = true if Vagrant::VERSION =~ /^1.8/
      end
    end
  end
end